# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PandaKitDemo' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'CocoaLumberjack'
pod 'MJRefresh'


end

target 'PandaKitDemoTests' do

end

target 'PandaKitDemoUITests' do

end

